// TIL_React/the_art_of_react/todo-app/src/components/TodoList.js
import TodoListItem from "./TodoListItem"
import './TodoList.scss'


const TodoList = ({ todos }) => {
    return (
        <div className="TodoList">
            {todos.map(todo => (
                <TodoListItem todo={todo} key={todo.id} />
            ))}
        </div>
    )
}

export default TodoList

// TIL_Vue/실습_파일/05_vue/todo-vuex-app/src/components/TodoList.vue
<template>
  <div>
    <TodoListItem
      v-for="(todo, index) in todos"
      :key="index"
      :todo="todo"
    />
    <!-- {{ todos }} -->
    <!-- {{ $store.state.todos }} -->
  </div>
</template>

<script>
import TodoListItem from '@/components/TodoListItem'

export default {
  name: 'TodoList',
  components: {
    TodoListItem,
  },
  computed: {
    todos() {
      return this.$store.state.todos
    }
  },
}
</script>

<style>

</style>
